apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: coffee
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: coffee/api
    docker:
      dockerfile: Dockerfile.prod
    requires:
    - image: coffee/api-builder
      alias: BASE

  - image: coffee/api-builder
    docker:
      cacheFrom:
      # googleCloudBuild replaces cache references to the artifact image with
      # the tagged image reference, useful for caching from the previous build.
      - coffee/api-builder
      dockerfile: Dockerfile
  googleCloudBuild:
    projectId: coffee-dev-351011
deploy:
  kubectl:
    manifests:
    - k8s-deployment.yaml
