apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-product-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffee-product
  template:
    metadata:
      labels:
        app: coffee-product
    spec:
      containers:
      - name: coffee-product
        image: coffee-product
        env:
        - name: PRICING_SVC_URI
          value: http://coffee-pricing-svc:1000
      imagePullSecrets:
      - name: artifact-repo-key
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-product-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: coffee-product
  ports:
  - port: 1000
    targetPort: 8080
    nodePort: 30002